# Generated by Django 6.0 on 2025-12-31 00:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('marketing', '0001_initial'),
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='freeitemvoucher',
            name='used_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='used_vouchers', to='orders.order'),
        ),
        migrations.AddField(
            model_name='freeitemvoucher',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='free_vouchers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='loyaltyaccount',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='loyalty', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='promotionredemption',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promo_redemptions', to='orders.order'),
        ),
        migrations.AddField(
            model_name='promotionredemption',
            name='promotion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='redemptions', to='marketing.promotion'),
        ),
        migrations.AddField(
            model_name='promotionredemption',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promo_redemptions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='referral',
            name='qualified_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qualifying_referrals', to='orders.order'),
        ),
        migrations.AddField(
            model_name='referral',
            name='referred',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='referral_received', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='referral',
            name='referrer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referrals_made', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='referralcode',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='referral_code', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='referral',
            name='referral_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='referrals', to='marketing.referralcode'),
        ),
        migrations.AddField(
            model_name='rewardledger',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reward_ledger', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='freeitemvoucher',
            index=models.Index(fields=['user', 'status', 'expires_at'], name='marketing_f_user_id_8b3d13_idx'),
        ),
        migrations.AddIndex(
            model_name='promotionredemption',
            index=models.Index(fields=['promotion', 'user', 'status'], name='marketing_p_promoti_acb5a1_idx'),
        ),
        migrations.AddIndex(
            model_name='promotionredemption',
            index=models.Index(fields=['order'], name='marketing_p_order_i_b93b17_idx'),
        ),
        migrations.AddConstraint(
            model_name='referral',
            constraint=models.CheckConstraint(condition=models.Q(('referrer', models.F('referred')), _negated=True), name='no_self_referral'),
        ),
        migrations.AddIndex(
            model_name='rewardledger',
            index=models.Index(fields=['user', 'created_at'], name='marketing_r_user_id_f80afe_idx'),
        ),
    ]
